### ISSUE TITLE
我发现很多网站不在意 SNI，因此似乎没必要暗渡陈仓的再去发送真实 SNI 信息，只需伪造 SNI 即可

### ISSUE THREAD

**Issue by forodo** [Macronut/phantomsocks#10]
大部分网站（除了个别 CDN），只需要伪造一个 SNI 中的域名（甚至都可以只用 IP），就可以正常连接访问了。
实际上现在很多工具都用到了这个原理，不过它们都是通过中间人本地反代，相比而言麻烦一点（签证书+速度损耗）。

因此我想，目前该工具这么多模式里，是否已经有这样做的模式了？（即**只伪造 SNI 域名**，不再紧跟发送真实 SNI 域名）
> 而且也可以避免部分网站服务器对当前伪造方式的兼容性问题。

好多模式我都不知道是干嘛的。。。

**Comment by awslawsl233** [comment]
> 目前该工具这么多模式里，是否已经有这样做的模式了？

没有。

**Comment by forodo** [comment]
@awslawsl233 那就蛋疼了。。。我这对 Go 了解有限，都不知道该怎么去改代码才能实现。。。

**Comment by Macronut** [comment]
The server doesn't care, but your browser or client does, so a MITM must be used to trick your browser or client, which is insecure and will be supported by fewer and fewer servers in the future.
