### ISSUE TITLE
How to start the service

### ISSUE THREAD

**Issue by snylonue** [Macronut/phantomsocks#11]
Platform: Windows 10
I tried `phantomsocks -socks 127.0.0.1:1080` and set prxoy in Firefox, but it doesn't work, returning `The proxy server is refusing connections` And task manager showed the program was not started
Then I ran `phantomsocks -install` and `phantomsocks -socks 127.0.0.1:1080 -start`, the program started but the proxy still didn't work
The config file is copied from TCPioneer

**Comment by forodo** [comment]
Please run **CMD** as an administrator and **CD** to the directory where the program is located, and then execute:
```
phantomsocks -socks 127.0.0.1:1080 -log 2
```
Tell me what the output is.

****

In addition, there are differences in the configuration files of TCPioneer and PhantomSocks, which cannot be directly copied and used.

**Comment by snylonue** [comment]
> Tell me what the output is.

Nothing

> which cannot be directly copied and used.

Here is the config used now
```
ttl=11

method=w-md5
github.com
.github.com
```

**Comment by forodo** [comment]
Nothing is output ?
Are you sure you are running PhantomSocks through **CMD** as **administrator** ?
Normally it should output the content.

****

Double-click to open the command line program directly. If an error is reported, it will stop and close the window directly. You cannot see any error message, so you must run it through CMD (administrator privileges) to see the error message.

****

**server=** in the configuration file should be required, for example:
``` ini
server=tcp://208.67.222.222:5353
ttl=11

method=w-md5
github.com
.github.com
```

****

Also, can you speak Chinese, my English is poor. . .

**Comment by snylonue** [comment]
>  Are you sure you are running PhantomSocks through CMD as administrator ?

I didn't notice cmd must be used and run it in powershell instead, where log was not shown.
It turned out that I didn't install `windivert` 

It'll be better if the log can be seen in any terminal or written to a file

我没注意到在 cmd 里启动才能看到日志，问题是没装 `windivert`

**Comment by XIU2** [comment]
记得用 WinDivert-1.4.3-A 这个版本的。
解压后只需要保留这两个文件并和 PhantomSocks.exe 放在一起。
```
WinDivert.dll
WinDivert64.sys
```

我们两个互相用翻译交流，真是醉了。。。

**Comment by snylonue** [comment]
What should I do if I want to bind another port rather than 1080
我应该怎么绑定 1080 以外的端口
`phantomsocks -socks 127.0.0.1:1080 -log 2` starts the server but never receives any request (I have changed the port in Firefox)
```
phantomsocks -socks 127.0.0.1:10805 -log 2
[ttl=11]
[server=udp://127.0.0.1:53]
[method=w-md5]
[method=s-seg,w-md5,https]
[default.conf]
Socks: 127.0.0.1:10805
interrupt
```
visit `127.0.0.1:10805` in Firefox returns `The connection was reset`

Maybe I should open another issue
也许我应该再开一个 issue

**Comment by forodo** [comment]
同样的配置文件，你使用 1080 端口就能连接，用 10805 就不行？

**Comment by Macronut** [comment]
> Platform: Windows 10
> I tried `phantomsocks -socks 127.0.0.1:1080` and set prxoy in Firefox, but it doesn't work, returning `The proxy server is refusing connections` And task manager showed the program was not started
> Then I ran `phantomsocks -install` and `phantomsocks -socks 127.0.0.1:1080 -start`, the program started but the proxy still didn't work
> The config file is copied from TCPioneer

If you need to start as a service, then you need to write StartFlags to phantomsocks.json in json format.

**Comment by forodo** [comment]
@Macronut Is there a format example?
Is the phantomsocks.json file only responsible for startup parameters?
