### ISSUE TITLE
CF系网站SSLstrip无法使用

### ISSUE THREAD

**Issue by lifegpc** [macronut/phantomsocks#13]
报错：`remote error: tls: handshake failure`

**Comment by lifegpc** [comment]
貌似不止Cloudflare, CloudFront也有问题
例如：
```
method=strip
www.ogurayui.jp
```

**Comment by macronut** [comment]
Why not just use https?

**Comment by lifegpc** [comment]
> Why not just use https?

这破网站会HTTPS返回HTTP的资源，导致浏览器拒绝加载（HTTPS本身没有任何问题

**Comment by imba-tjd** [comment]
> 这破网站会HTTPS返回HTTP的资源

可以用header editor或者httpseverywhere重定向到https
