### ISSUE TITLE
想问一下dns服务器的问题

### ISSUE THREAD

**Issue by wuyu8512** [macronut/phantomsocks#18]
如果为域名指定了ip，则dns请求会直接类似失败，请求方无法得到ip
![image](https://user-images.githubusercontent.com/33444499/156884020-a30b90c5-d5df-49d1-81b8-fcb17d894c0d.png)

ps：程序运行在arm的openwrt上，客户端是window11

**Comment by wuyu8512** [comment]
不是很懂go
似乎把dns.go文件里

` return BuildLie(request, qtype, answer.Index)` 这句改成 `return BuildResponse(request, qtype, 3600, answer.Addresses)` 就好了

**Comment by macronut** [comment]
From [9deb074](https://github.com/macronut/phantomsocks/commit/9deb0743032e7c36f4f66753ccb9cac9e10d71dd) you need to set the prefix of the IP in the fake DNS record yourself and be consistent with the iptables rules.

**Comment by macronut** [comment]
> 不是很懂go 似乎把dns.go里的两个 `return BuildLie(request, qtype, answer.Index)` 改成 `return BuildResponse(request, qtype, 3600, answer.Addresses)` 就好了
> 
> 然后还有个问题，透明代理到软件的时候是只有ip的，是否考虑在dns返回解析结果的时候，顺便把ip也加入处理列表？

No, this is another implementation, which is used by GhosTCP, may be supported later...

**Comment by wuyu8512** [comment]
理解了，但这样似乎就代表，只有指定了ip的域名才会被处理？
