### ISSUE TITLE
关于配置文件的IP解析

### ISSUE THREAD

**Issue by wuyu8512** [macronut/phantomsocks#19]
https://github.com/macronut/phantomsocks/blob/6354abdb569daad723043784e21c416ebcdd596c/phantomtcp/phantom.go#L488

这段解析ip的代码让我有点疑惑，`ResolveTCPAddr` 这个函数只要不带端口，就一定会返回错误
如果是 CIDR 的ip表示法，在这里就一定会走到下面的 `DomainMap[keys[0]] = CurrentServer`
根本走不到 `ParseCIDR` ，然后软件的修改数据包判断似乎根本不管CIDR表示法的？

**Comment by macronut** [comment]
OK, when I have time to fix it.
