### ISSUE TITLE
[BUG] dns解析时出现大量循环

### ISSUE THREAD

**Issue by wuyu8512** [macronut/phantomsocks#21]
![image](https://user-images.githubusercontent.com/33444499/158003252-bb236e60-9821-4fe2-ae13-7ac0b0558ed3.png)
![image](https://user-images.githubusercontent.com/33444499/158003257-48e29c7f-0a01-4145-9636-ecb48daa31cd.png)

`log.Println(i)` 是我自己加上去的，发现他停不下来了，导致了大量的gc，然后把cpu吃满了

**Comment by wuyu8512** [comment]
经过排查，发现是n一直为0导致的

**Comment by macronut** [comment]
[Add protection to prevent incorrect DoT response](https://github.com/macronut/phantomsocks/commit/4b894b3af238317c2beea66e59321a09c0ece2b2)
