### ISSUE TITLE
error on macos 12.2.1

### ISSUE THREAD

**Issue by Rastinition** [macronut/phantomsocks#23]
Using the default config as is in this repo and latest phantomsocks

```
./phantomsocks -device en0 -socks 127.0.0.1:1681 -log 3 -c default.conf

server=udp://8.8.8.8:53
ttl=11
server=tls://8.8.4.4:853
method=none
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1222fa7]

goroutine 1 [running]:
github.com/macronut/phantomsocks/phantomtcp.LoadConfig({0x7ff7bfeffb43, 0x3a})
	/Users/v/git/phantomsocks/phantomtcp/phantom.go:496 +0x1587
main.StartService()
	/Users/v/git/phantomsocks/main.go:179 +0x2ee
main.main()
	/Users/v/git/phantomsocks/main.go:309 +0x6da
```

**Comment by Rastinition** [comment]
I will rollback to 9c68545 commit, from this version to 6354abd phantomsocks cannot build.

From 6354abd to 1accf11 there's always an error `example.com connection does not exist`

From 4b894b3 on the above error would occur.

**Comment by macronut** [comment]
From [a8db67d](https://github.com/macronut/phantomsocks/commit/a8db67dbebb04ad7b84569c9304f4ea1f9771e37) it's just a normal proxy if it doesn't have any tags.

**Comment by Rastinition** [comment]
Fine, I added `-tags pcap` when build to solve this.
