### ISSUE TITLE
tsinghua doh can't work

### ISSUE THREAD

**Issue by rubnet** [macronut/phantomsocks#30]
Socks: line.me 443 &{168xxxxx 15 0 512 https://101.6.6.6:8443/dns-query }
POST /dns-query HTTP/1.1
Host:
Accept: application/dns-message
Content-Type: application/dns-message
Connection: close
Content-Length: 25

HTTP/1.1 400 Bad Request
Server: nginx/1.18.0
Date:  xxxxxx
Content-Type: text/html
Content-Length: 157
Connection: close

**Comment by macronut** [comment]
Fixed
