### ISSUE TITLE
Take over all domains

### ISSUE THREAD

**Issue by XCwosjw** [macronut/phantomsocks#33]
Is there a way to make all domain names handled by phantomsocks? It is too troublesome to add one by one to the conf.

**Comment by Longway22** [comment]
> 为此我略微修改了phantomsocks，现在对于配置文件中不存在的域名，也会通过cloudflare dns解析，不需要再手动添加到配置文件中。详情见代码及default.conf.

Read this?

https://2047.one/t/16729

**Comment by XCwosjw** [comment]
I think it's useful,thanks

**Comment by macronut** [comment]
[phantomsocks](https://github.com/macronut/phantomsocks)/[phantomtcp](https://github.com/macronut/phantomsocks/tree/master/phantomtcp)/phantom.go +446

**Comment by XCwosjw** [comment]
I think you may not understand what I mean, currently if you want phantomsocks to process packets for a domain you have to add the domain to the conf file, for example, in this example phantomsocks will only handle Pixiv related domains
```
server=udp://192.168.1.1:53
method=w-md5,s-seg,https
#Pixiv
pixiv.net
.pixiv.net
i.pximg.net
```
but it is very troublesome to add domains one by one, I want to know if there is a way for phantomsocks to process packets for all domains (even if that domain is not in the conf file)

**Comment by macronut** [comment]
DefaultServer is what is used for all domains that are not in the config.

**Comment by XCwosjw** [comment]
It worked,Thanks!
