### ISSUE TITLE
Linux mips rawsocket version run some days.The log show connection does not exist

### ISSUE THREAD

**Issue by rubnet** [macronut/phantomsocks#34]
run command
`./phantomsocks_mips -c ./default.conf -socks 192.168.1.1:1081 -device ppp8 -log 2
`
test via `curl https://line.me/robots.txt -x socks5h://192.168.1.1:1081`

The log show normal at first day. But  it  show connection does not exist after some days

```
Socks: line.me 443 &{4 12 0 512 https://146.112.41.2/dns-query  }
203.104.138.138 443 <nil>
 after some days
Socks: line.me 443 &{4 12 0 512 https://146.112.41.2/dns-query  }
203.104.138.138 443 <nil>
line.me connection does not exist
```
I think **ppp8 's ipv6 address update** result it can't listen connection

**Comment by macronut** [comment]
because there is no real-time detection of the interface IP, it is need to restarted if the IP changes.
It may be added recently.
