### ISSUE TITLE
关于透明代理

### ISSUE THREAD

**Issue by wuyu8512** [macronut/phantomsocks#35]
请问是否有可能完全抛弃vaddrprefix，更直白来说我希望返回真实的ip地址，以及所有的连接都有办法通过这个软件

我发现redirect函数里使用了GetSNI第二次获取了域名，假设对于所有连接都通过这个方法来得到域名，那我们就可以得到对应的PhantomInterface
似乎最大的问题是如何解决流量回环？

**Comment by macronut** [comment]
What is the need to access without using a domain name but with a domain name in the SNI?

**Comment by wuyu8512** [comment]
抱歉，我意思是希望软件的dns服务器可以返回真实ip
我想法是即便不借助vaddrprefix，我们也可以通过GetSNI和GetHost来获得域名，从而得到PhantomInterface

**Comment by macronut** [comment]
In the case of ESNI ECH HTTP/3 can also know the original domain name and select the interface, multiple IP servers can also detect the available IP by proxy, while avoiding exposing the real IP to untrust clients, extra more than once to get SNI just to avoid the DNS cache residue.
Returning the real IP does not bring benefits, but sacrifices the above function, so why do it?
