### ISSUE TITLE
考虑通过环境变量设置工作目录

### ISSUE THREAD

**Issue by wuyu8512** [macronut/phantomsocks#38]
openwrt的procd不支持设置工作目录有点难受

**Comment by lilith-rong** [comment]
大佬，能教教openwrt怎么设置这个软件嘛？

**Comment by wuyu8512** [comment]
@lilith-rong 无非就是设置Dns和流量转发，dnsmasq里设置转发到这个软件，其他设备的Dns指向OpenWrt
然后就是转发流量到你设置的redirect端口咯
比如说
```
iptables -t nat -A OUTPUT -d 6.0.0.0/8 -p tcp -j REDIRECT --to-port 6
iptables -t nat -A PREROUTING -d 6.0.0.0/8 -p tcp -j REDIRECT --to-port 6
```

**Comment by lilith-rong** [comment]
@wuyu8512 感谢大佬解惑，我去尝试编译一个摔到我软路由上面去用了

**Comment by macronut** [comment]
https://github.com/macronut/phantomsocks/commit/14291e2c889efb4fba5ead598acbb31d0077f948
