### ISSUE TITLE
代理策略是否过于严格

### ISSUE THREAD

**Issue by wuyu8512** [macronut/phantomsocks#40]
SNIProxy：
无法得到域名就断连了

QUICProxy：
不是QUIC协议就断连了

TProxy：
不是虚拟地址就断连了

这里可以后退成不走Proxy的正常流量吧

**Comment by macronut** [comment]
https://en.m.wikipedia.org/wiki/Reverse_proxy

Reverse proxy must get Host to be able to proxy
