### ISSUE TITLE
 Cannot compile:

### ISSUE THREAD

**Issue by Yang-0326-dell** [macronut/phantomsocks#42]
build command-line-arguments: cannot load net/netip: malformed module path "net/netip": missing dot in first path element

**Comment by macronut** [comment]
Upgrade Golang to 1.18 or highter.

**Comment by orency** [comment]
> Upgrade Golang to 1.18 or highter.

Just 1.18 only .Due to some change in gvisor, 1.19 can not compile successfully for now.
1.19 needs this [commit](https://github.com/WireGuard/wireguard-go/pull/55)
but it has not been merge to master temporarily.
