### ISSUE TITLE
go get github.com/macronut/phantomsocks    提示 golang.zx2c4.com/wireguard/tun/netstack: golang.zx2c4.com/wireguard/tun/netstack@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000         

### ISSUE THREAD

**Issue by zhenxiyang** [macronut/phantomsocks#43]
在mac上使用go get github.com/macronut/phantomsocks    提示 golang.zx2c4.com/wireguard/tun/netstack: golang.zx2c4.com/wireguard/tun/netstack@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000         

![截屏2022-08-21 14 03 00](https://user-images.githubusercontent.com/80905507/185778309-e6ce3c39-7b85-469e-910b-9e4a7460f715.png)

**Comment by macronut** [comment]
ok, wireguard is not included by default now.
