### ISSUE TITLE
Quic Support

### ISSUE THREAD

**Issue by wuyu8512** [macronut/phantomsocks#44]
在最新版的Chrome(105.0.5195.127)中似乎无法获取Quic Sni了

然后顺便再问一下，IETF QUIC有办法获取SNI吗
`docker run --rm -it sancraftdev/curl-quic --http3 -sL https://cloudflare.com` 用这个试了一下也获取不到SNI

**Comment by macronut** [comment]
It is already encrypted since Q046, please get the original IP through TProxy
