### ISSUE TITLE
怎么把网卡流量全部重定向到软件里面？

### ISSUE THREAD

**Issue by 821938089** [macronut/phantomsocks#50]
readme写的这个配置我试了一下没有用
```json
Windows(windivert):
config.json:
    "vaddrprefix": 6,
    "proxy": "redirect://0.0.0.0:6",
    "services": [
        {
            "name": "Redirect",
            "protocol": "redirect",
            "address": "0.0.0.0:6"
        }
    ]
```

**Comment by macronut** [comment]
windivert mode only redirect virtual addresses, you can use other transparent proxies or use Socks mode directly.

**Comment by zhangyz1997** [comment]
> windivert mode only redirect virtual addresses, you can use other transparent proxies or use Socks mode directly.

is there any suggestions on transparent proxies on Windows to use windivert mode?
