### ISSUE TITLE
Due to technical limitations, a compiled Linux version is required由于技术限制，需要一个编译好的linux版

### ISSUE THREAD

**Issue by Atlantis829** [macronut/phantomsocks#52]
Request a software distribution of amd64 for Ubuntu/Linux
请求一个适用于Ubuntu/linux的amd64的软件发行版
thanks a lot！
感激不尽！

**Comment by macronut** [comment]
It is very easy to cross-compile golang and there are many combinations of platforms and tags, please compile it yourself.
