### ISSUE TITLE
用于对抗移动的eu.org域名SNI阻断，这个对基于websocket的vless协议管用吗？

### ISSUE THREAD

**Issue by daiaji** [macronut/phantomsocks#67]
有人报告了PhantomSocks作为vless的前置代理无法起作用。

**Comment by UjuiUjuMandan** [comment]
你都用 phantomsocks 了，还代理个毛线啊，直接直连不好吗？

**Comment by daiaji** [comment]
> 你都用 phantomsocks 了，还webscoket、vless、代理个毛线啊，直接直连不好吗？

也不是所有的网站都是SNI RST,还有黑洞路由呢，比如电报就是因为用IP连接，直接吃了黑洞路由。

基本上就是eu.org吃了移动的SNI RST,所以部署在这个域名的vless就用不了了。

**Comment by UjuiUjuMandan** [comment]
> 但有人回报PhantomSocks似乎对vless不好使。

本来就不是设计这么用的，vless 是 HTTPS 吗？和访问网站的 HTTPS 一样吗？

**Comment by daiaji** [comment]
> > 但有人回报PhantomSocks似乎对vless不好使。
> 
> 本来就不是设计这么用的，vless 是 HTTPS 吗？和访问网站的 HTTPS 一样吗？

vless和trojan一样无加密，一般是嵌套在websocket里外套TLS用，然后走CDN，看起来就是一个用tls加密的websocket。

**Comment by UjuiUjuMandan** [comment]
PS 的修改是在 TCP 层，不应该有和 WebSocket 有关的问题。

**Comment by UjuiUjuMandan** [comment]
应该和应用层的 WebSocket 没关系。

要么没成功 desync 连接，要么服务器把伪包当真了。

用 curl 试试看嘛，能不能建立 TLS 连接？

**Comment by daiaji** [comment]
移动暂时又把eu.org放出来了，只能下次再看看了。

**Comment by macronut** [comment]
https://en.wikipedia.org/wiki/WebSocket
